In [ ]:
import numpy as np

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros(3) #crea un array compuesto por "ceros"
#Útil para crear una estructura previa
np.zeros((10,5)) #crea un arreglo matricial de 10 filas por 5 columnas

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#quiero 100 datos de cero a diez
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
#crea matriz con la diagonal principal
#para el algebra lineal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#numero random entre 0 y 1 
np.random.rand()

0.3582610533685082

In [14]:
#array de una unica dimension
#genera una array con numeros aleatorios de una sola dimension 
np.random.rand(4)

array([0.47155567, 0.91750797, 0.02024353, 0.01776276])

In [16]:
#el siguietne genera una estructura matricial con vcalores aleatorios 
np.random.rand(4,4)

array([[0.18839355, 0.08242614, 0.7305546 , 0.28677029],
       [0.75389804, 0.10886829, 0.97832675, 0.41736373],
       [0.66534489, 0.79402144, 0.77973938, 0.25637826],
       [0.99094641, 0.47226662, 0.68895072, 0.74769955]])

In [18]:
#entero aleatorio entre 1 y 15
np.random.randint(1,15)

14

In [22]:
#valores enteros de 1 a 100 
#en un matriz de 10x10
np.random.randint(1,100,(10,10))

array([[64, 60,  9, 70, 88,  5, 70, 99, 23, 20],
       [53, 38, 31, 94, 99, 46, 51, 43, 92, 42],
       [99, 19, 46, 28, 51, 57, 26,  7, 71, 78],
       [83, 92, 83, 16, 11, 82, 71,  2, 79, 95],
       [70,  5,  3,  3, 92, 27, 21, 98, 90, 17],
       [16, 53, 87, 23, 97, 95, 85, 58, 11, 88],
       [98, 83, 78, 64, 39, 80, 53, 20, 54, 49],
       [68, 48, 45, 22, 57, 74, 83, 68, 24, 29],
       [69, 12, 69, 31, 59,  3, 44, 11,  7, 50],
       [59,  1, 55, 27, 70, 33, 75, 10, 61, 76]])

In [24]:
#para tener una amtriz con un numero predeterminado 
np.full((3,3),7)


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [25]:
#Random choice genera un numeros aleatorios de un set de numeros definidos.
np.random.choice([1,3,5,7,9], size=(3, 5))

array([[1, 7, 9, 3, 9],
       [3, 1, 9, 9, 9],
       [3, 7, 7, 5, 9]])