# Dimensiones

indica el numero de dimensiones 
```
ndim 
```



In [ ]:
scalar=np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
vector=np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz=np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
matriz=np.array([[[1,2,3],[4,5,6],[7,8,9,],[0,45,2]],[[1,2,3],[4,5,6],[7,8,9,],[0,45,2]]])
print(matriz)
matriz.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0 45  2]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0 45  2]]]


3

---
#Agregar o eliminar dimensiones 

Agrega el numero de dimensiones que uno desea de una lista 
```
ndim=10
```

axis cuando es cero, se grega una fila y el axis uno se agrega una columna 
```
axis=0 ; axis=1
```






In [ ]:
vector=np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

---

con esta función permite expandir el tensor
```
np.expand_dims 
```



In [ ]:
expand=np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector, vector.ndim)
vector_2=np.squeeze(vector)

---
Con esto comprime el numero de dimensiones correcto que no se esten usando 


```
np.squeeze(vector)
```
En el caso de abajo comprime 10 dimensiones a una porque no se estan usando 9 dimensiones 



In [ ]:
print(vector, vector.ndim)
vector_2=np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


#Reto
1. Definir un tensor con al menos 5 dimensiones
2. Sumarle una dimensión en cualquiera de sus ejes
3. Borrar las dimensiones que no se usan 

In [ ]:
tensor=np.array(([[1,2,3],[4,5,6],[7,8,9]]), ndmin=5)
print(tensor)
tensor.ndim

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]


5

In [ ]:
tensor_1=np.expand_dims(tensor, axis=0)
print(tensor_1)
tensor_1.ndim

[[[[[[1 2 3]
     [4 5 6]
     [7 8 9]]]]]]


6

In [ ]:
tensor_2=np.squeeze(tensor_1)
print(tensor_2)
tensor_2.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2