In [4]:
#shape 
#indica la forma que tiene un arreglo 
#la forma de un arreglo entrega la estrctura de un arreglo, que tan coroto es un arreglo y como se puede ingresar a el y como arreglarlo 
import numpy as np

In [3]:
arr = np.array([13, 6, 3, 5, 10])
np.max(arr)

13

In [ ]:
arr=np.random.randint(1,10, (3,2))
arr

array([[4, 2],
       [2, 6],
       [6, 9]])

In [ ]:
#cuantas filas y columnas se tiene 
arr.shape

(3, 2)

In [ ]:
#cambiar la forma establecida de mi array
arr.reshape(1,6)

array([[4, 2, 2, 6, 6, 9]])

In [ ]:
np.reshape(arr, (1,6))

array([[4, 2, 2, 6, 6, 9]])

In [ ]:
arr

array([[4, 2],
       [2, 6],
       [6, 9]])

In [ ]:
#Se puede hacer un reshape como lo haría C.
np.reshape(arr, (2,3), "C")

array([[4, 2, 2],
       [6, 6, 9]])

In [ ]:
#También se puede hacer reshape a como lo haría Fortran.
np.reshape(arr, (2,3), "F")

array([[4, 6, 6],
       [2, 2, 9]])

In [ ]:
#Además existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en C.
np.reshape(arr, (2,3), "A")

array([[4, 2, 2],
       [6, 6, 9]])

In [ ]:
#no se puede cmabiar la forma, debe tener una forma de 6 elementos y la forma debe mantener esos elementos