In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
trozo=arr[0:6]
trozo

array([0, 1, 2, 3, 4, 5])

In [4]:
#cambia todos los valores a cero
trozo[:]=0
trozo

array([0, 0, 0, 0, 0, 0])

In [5]:
#con lo siguiente va a dar cuenta que se cmabio el array, no solo una parte
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [6]:
#.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.
arr_copy=arr.copy()

In [7]:
arr_copy[:]=100

In [8]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])