In [1]:
import numpy as np

In [4]:
arr=np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [5]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
#entrega valor booleano a todos los valores dentro del array que cumplen o no cumplen con la condicion
indices_cond=arr>5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [9]:
#muestra una lista con valores que cumplen con la condicion 
arr[indices_cond]


array([ 6,  7,  8,  9, 10], dtype=int8)

In [11]:
#esto tambien entrega el mismo resultado
arr[arr>5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [12]:
#otra condicional con valores AND
arr[(arr>5)&(arr<9)]

array([6, 7, 8], dtype=int8)

In [13]:
arr[arr>5]=99

In [14]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

In [19]:
#ahora con una matriz
arr=np.random.rand(7,3)
arr

array([[0.92686627, 0.32869631, 0.09770272],
       [0.58561344, 0.26094064, 0.41059467],
       [0.10122688, 0.12131144, 0.39449165],
       [0.32893492, 0.29701948, 0.65130217],
       [0.76999011, 0.35957629, 0.53359497],
       [0.02607723, 0.42659121, 0.03078013],
       [0.66143095, 0.06036348, 0.7729006 ]])

In [20]:
arr[arr<0.3]=0
arr

array([[0.92686627, 0.32869631, 0.        ],
       [0.58561344, 0.        , 0.41059467],
       [0.        , 0.        , 0.39449165],
       [0.32893492, 0.        , 0.65130217],
       [0.76999011, 0.35957629, 0.53359497],
       [0.        , 0.42659121, 0.        ],
       [0.66143095, 0.        , 0.7729006 ]])

In [21]:
arr[arr>0.3]=1
arr

array([[1., 1., 0.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])