In [2]:
import numpy as np

In [5]:
lista=[1,2]
lista

[1, 2]

In [6]:
lista*2

[1, 2, 1, 2]

In [7]:
lista*8

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [8]:
arr=np.arange(0,10)
arr2=arr.copy()

Operaciones

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr*arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
matriz=arr.reshape(2,5)
matriz2=matriz.copy()

In [16]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
matriz+matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [18]:
matriz-matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
#producto punto 
np.matmul(matriz,matriz2)
#arroja un error porque se resuleve con la Transpuesta (T)

ValueError: ignored

In [21]:
  #soluciona el problema del producto punto
  matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [22]:
#otra manera de solucoinar problema punto 
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])